# ==============================================================================
# MODULE: run.py
# PURPOSE: Project entry point and environment setup bootstrapper.
# VERSION: 3.2 (Corrected version validation logic)
# AUTHOR: Islam Ebeid
# ==============================================================================

import argparse
import sys
import subprocess

# --- FIX: Suppress the Hugging Face Tokenizers parallelism warning ---
# This is a common warning in multiprocessing environments. Setting this environment
# variable to 'false' silences the warning and is the recommended practice.
import os
import dask
import time
from pathlib import Path
from source.utils.fs.cleaner import ProjectCleaner
os.environ["TOKENIZERS_PARALLELISM"] = "false"
# Local imports must come after the environment is validated and potentially set up.
# We make an exception for Config and FileLogger which are needed for the bootstrapper itself.
from configuration.config import Config # noqa
from source.utils.logging.file_logger import FileLogger

# --- Configuration ---
# This YAML file is the "source of truth" for a valid environment.
# It is generated by setup.py upon successful completion.
ENVIRONMENT_YML_FILE = "environment.yml"

def is_environment_valid(verbose: bool = True) -> bool:
    """
    Performs a direct, robust check for critical packages in the environment.
    This is more reliable than checking for a generated file.
    """
    if verbose: print("--- Validating environment by checking for critical packages... ---")
    try:
        # Check for the most important and complex dependencies.
        # If these exist, it's highly likely the environment is correctly set up.
        import torch
        import tensorflow
        import pycuda.driver
        import torch_geometric
        if verbose: print("--- Environment validation PASSED. ---")
        return True
    except ImportError as e:
        if verbose:
            print(f"--- Validation FAILED. Missing critical package: {e.name} ---")
            print("--- Assuming setup is required. ---")
        return False
    except Exception as e:
        if verbose:
            print(f"--- An unexpected error occurred during validation: {e} ---")
            print("--- Assuming setup is required. ---")
        return False

def run_setup():
    """Executes the main setup script to build the Conda environment."""
    print("\n" + "="*80)
    print("--- Environment is incomplete. Running setup script... ---")
    print("--- This is a one-time process and may take several minutes. ---")
    print("="*80 + "\n")
    try:
        # Use sys.executable to ensure we use the python from the current (minimal) env
        # to run the setup script. This is the most robust method.
        setup_script_path = "configuration/setup.py"
        result = subprocess.run([sys.executable, setup_script_path], check=True)
        if result.returncode == 0:
            print("\n" + "="*80)
            print("--- ✅ Environment setup completed successfully. ---")
            print("--- The application will now start. ---")
            print("="*80 + "\n")
            return True
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print("\n" + "!"*80)
        print(f"--- ❌ FATAL: Environment setup script failed: {e} ---")
        print("--- Please check the logs above for details. ---")
        print("!"*80 + "\n")
    return False

if __name__ == "__main__":
    # --- DEFINITIVE FIX: This script is now just an environment validator or a simple launcher ---
    parser = argparse.ArgumentParser(description="Run pipeline or validate environment.")
    parser.add_argument('--validate-env-only', action='store_true', help='Only validate the environment and exit with a status code.')
    args = parser.parse_args()

    if args.validate_env_only:
        if is_environment_valid():
            sys.exit(0)  # Success
        else:
            sys.exit(1)  # Failure
    else:
        # --- NEW: Perform cleaning at the start of a run ---
        # This makes the Python script the single source of truth for a clean run,
        # --- FIX: Disabling the cleaning of the results directory as per user request ---
        # This will preserve intermediate files from previous runs.
        # project_root_path = Path(__file__).resolve().parent
        # ProjectCleaner.clean_project(project_root_path)
        print("--- INFO: Automatic cleaning of the 'results' directory has been disabled. ---")

        # --- DEFINITIVE FIX: Validate the environment and run setup if needed ---
        if not is_environment_valid():
            if not run_setup():
                sys.exit(1) # Exit if the setup process failed

        # Now, we can safely assume the environment is valid and proceed.
        base_config = Config()

        # --- DEFINITIVE FIX: Create a unique output directory for each run ---
        # This prevents subsequent runs from overwriting the results of previous ones.
        run_id = f"run_{time.strftime('%Y%m%d_%H%M%S')}"
        base_config.BASE_OUTPUT_DIR = base_config.BASE_OUTPUT_DIR / run_id
        # Re-initialize all path attributes to use this new base directory.
        base_config._setup_paths()

        logger = FileLogger(base_config.LOG_DIR, enabled=base_config.ENABLE_FILE_LOGGING)

        # --- DEFINITIVE FIX for "No space left on device" and "FileNotFoundError" ---
        # Configure Dask's temporary directory globally at the start of the application.
        # This ensures that ALL Dask operations (in any module) use a safe location
        # within the project's results directory, preventing crashes due to a full /tmp partition.
        dask_temp_dir = base_config.BASE_OUTPUT_DIR / "dask_temp"
        dask.config.set({'temporary_directory': str(dask_temp_dir)})
        # CRITICAL: Ensure the directory exists before any Dask operations are called.
        dask_temp_dir.mkdir(parents=True, exist_ok=True)

        with logger:
            from source.entry.main import PipelineOrchestrator
            orchestrator = PipelineOrchestrator(base_config)
            orchestrator.run()