# ==============================================================================
# MODULE: run.py
# PURPOSE: Project entry point and environment setup bootstrapper.
# VERSION: 3.2 (Corrected version validation logic)
# AUTHOR: Islam Ebeid
# ==============================================================================

import json
import subprocess
import sys
from pathlib import Path
from typing import Dict

# --- FIX: Suppress the Hugging Face Tokenizers parallelism warning ---
# This is a common warning in multiprocessing environments. Setting this environment
# variable to 'false' silences the warning and is the recommended practice.
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"
# Local imports must come after the environment is validated and potentially set up.
# We make an exception for Config and FileLogger which are needed for the bootstrapper itself.
from configuration.config import Config # noqa
from source.utils.logging.file_logger import FileLogger
from source.utils.data.data_utils import DataUtils

# --- Configuration ---
# This YAML file is the "source of truth" for a valid environment.
# It is generated by setup.py upon successful completion.
ENVIRONMENT_YML_FILE = "environment.yml"


def is_environment_valid() -> bool:
    """
    Performs a direct, robust check for critical packages in the environment.
    This is more reliable than checking for a generated file, which might be
    missing due to an interrupted setup or other issues.
    """
    try:
        print("--- Validating environment by checking for critical packages... ---")
        # Check for the most important and complex dependencies.
        # If these exist, it's highly likely the environment is correctly set up.
        import torch
        import tensorflow
        import pycuda.driver
        import torch_geometric
        print("--- Environment validation PASSED. ---")
        return True
    except ImportError as e:
        print(f"--- Validation FAILED. Missing critical package: {e.name} ---")
        print("--- Assuming setup is required. ---")
        return False
    except Exception as e:
        print(f"--- An unexpected error occurred during validation: {e} ---")
        print("--- Assuming setup is required. ---")
        return False


def run_command(command: list[str]):
    """Runs a command and streams its output, exiting on failure."""
    try:
        # Let the subprocess inherit stdout/stderr directly so that
        # interactive elements like tqdm can render correctly.
        process = subprocess.Popen(
            command,
            text=True,
            encoding='utf-8',
            errors='replace'
        )

        process.wait()
        if process.returncode != 0:
            print(f"\n--- Command failed with exit code {process.returncode}. Aborting. ---")
            sys.exit(process.returncode)

    except FileNotFoundError:
        print(f"--- ERROR: Command '{command[0]}' not found. Is it in your PATH? ---")
        sys.exit(1)
    except Exception as e:
        print(f"--- An unexpected error occurred while running a command: {e} ---")
        sys.exit(1)


if __name__ == "__main__":
    # Initialize config and logger at the very beginning to capture all output.
    base_config = Config()
    logger = FileLogger(base_config.LOG_DIR, enabled=base_config.ENABLE_FILE_LOGGING)

    # Use the logger as a context manager to ensure it's always closed properly.
    with logger:
        project_root = Path(__file__).parent.resolve()

        # 1. Validate the environment. If it's not valid, run the setup script.
        # The output of the setup script will be captured by the logger.
        if not is_environment_valid():
            # --- NEW: Proactive memory check and cleanup for graceful failure ---
            # The setup process is memory-intensive. Check for sufficient RAM to avoid an OOM kill.
            # We also clean up leftover temp files from any previous, crashed installation attempt.
            print("\n--- Performing pre-installation checks... ---")
            required_ram_gb = 8  # A conservative estimate for the setup process
            if not DataUtils.has_enough_memory(required_ram_gb, "Environment Setup"):
                print("\n--- FATAL: Not enough memory to safely run the installation. ---")
                print("--- Please free up system resources or run on a machine with more RAM. ---")
                sys.exit(1)

            temp_script_path_sh = project_root / "temp_setup_script.sh"
            if temp_script_path_sh.exists():
                print(f"  - Found and removed leftover temporary script: {temp_script_path_sh.name}")
                temp_script_path_sh.unlink()
            temp_script_path_bat = project_root / "temp_setup_script.bat"
            if temp_script_path_bat.exists():
                print(f"  - Found and removed leftover temporary script: {temp_script_path_bat.name}")
                temp_script_path_bat.unlink()

            print("\n--- Environment is invalid or not yet set up. Running installation... ---")
            print("--- This may take several minutes. All output is being logged. ---")

            setup_script_path = str(project_root / "configuration" / "setup.py")
            run_command([sys.executable, setup_script_path])

            print("\n--- Environment setup complete. Re-validating... ---")
            if not is_environment_valid():
                print("\n--- FATAL: Environment is still invalid after setup. Please check the logs. ---")
                sys.exit(1)
            print("--- Re-validation successful. Starting the main pipeline... ---")
        else:
            print("--- Environment is already set up and valid. Starting main pipeline... ---")

        # --- NEW: Data Validation and Restoration Logic ---
        # This replaces the simple call to setup_data in main.py
        from configuration.manager import DataManager
        data_manager = DataManager(base_config)

        print("\n--- Verifying local data integrity ---")
        is_data_valid = data_manager.validate_data_from_manifest()

        if not is_data_valid:
            print("\n--- Local data is invalid or missing. Attempting to restore from cache... ---")
            restored_ok = data_manager.restore_data_from_bundle()
            if not restored_ok:
                print("\n" + "!" * 80)
                print("!!! FATAL: Data is missing or corrupt, and could not be restored from cache. !!!")
                print("!!! Please run the one-time setup script to download and process all data: !!!")
                print("!!!                                                                          !!!")
                print("!!!   bash configuration/reset.sh                                            !!!")
                print("!" * 80)
                sys.exit(1)
        else:
            print("--- Local data is valid. ---")

        # 3. Run the main pipeline script as a separate process.
        # This ensures it runs in the now-validated environment with a clean state.
        main_script_path = str(project_root / "source" / "entry" / "main.py")
        run_command([sys.executable, main_script_path])