# ==============================================================================
# MODULE: run.py
# PURPOSE: Project entry point and environment setup bootstrapper.
# VERSION: 2.0 (Added environment validation against environment.yml)
# AUTHOR: Islam Ebeid
# ==============================================================================

import json
import subprocess
import sys
from pathlib import Path

# --- Configuration ---
# This YAML file is the "source of truth" for a valid environment.
# It is generated by setup.py upon successful completion.
ENVIRONMENT_YML_FILE = "environment.yml"


def is_environment_valid(project_root: Path) -> bool:
    """
    Checks if the current Conda environment matches the required packages
    and versions specified in the environment.yml file.
    """
    env_file = project_root / ENVIRONMENT_YML_FILE
    if not env_file.exists():
        print("--- Validation file not found. Assuming first-time setup. ---")
        return False

    try:
        # 1. Get the list of currently installed packages from Conda
        print("--- Validating current environment... ---")
        result = subprocess.run(
            ["conda", "list", "--json"],
            capture_output=True, text=True, check=True
        )
        installed_packages = {pkg['name']: pkg['version'] for pkg in json.loads(result.stdout)}

        # 2. Parse the required packages from the environment.yml file
        # We use a simple parser to avoid depending on PyYAML before it's installed.
        with open(env_file, 'r') as f:
            lines = f.readlines()

        required_conda = []
        required_pip = []
        in_pip_section = False
        for line in lines:
            line = line.strip()
            if line == "dependencies:":
                continue
            if "pip:" in line:
                in_pip_section = True
                continue
            if not line or line.startswith('#') or line.startswith("name:") or line.startswith("channels:") or line.startswith("prefix:"):
                continue

            # Handle package strings like 'numpy=1.26.4=pypi_0' or 'numpy==1.26.4'
            package_name = line.split('=')[0].replace('-', '').strip()
            if in_pip_section:
                required_pip.append(package_name)
            else:
                required_conda.append(package_name)

        # 3. Check if all required packages are installed
        for req_pkg in required_conda + required_pip:
            if req_pkg not in installed_packages:
                print(f"--- Validation FAILED: Required package '{req_pkg}' is not installed. ---")
                return False

        print("--- Environment validation PASSED. ---")
        return True

    except (subprocess.CalledProcessError, json.JSONDecodeError, FileNotFoundError) as e:
        print(f"--- Could not validate environment due to an error: {e} ---")
        print("--- Assuming setup is required. ---")
        return False
    except Exception as e:
        print(f"--- An unexpected error occurred during validation: {e} ---")
        return False


def run_command(command: list[str]):
    """Runs a command and streams its output, exiting on failure."""
    try:
        process = subprocess.Popen(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
            universal_newlines=True
        )
        if process.stdout:
            for line in process.stdout:
                print(line, end='')
        process.wait()
        if process.returncode != 0:
            print(f"\n--- Command failed with exit code {process.returncode}. Aborting. ---")
            sys.exit(process.returncode)
    except FileNotFoundError:
        print(f"--- ERROR: Command '{command[0]}' not found. Is it in your PATH? ---")
        sys.exit(1)
    except Exception as e:
        print(f"--- An unexpected error occurred: {e} ---")
        sys.exit(1)


if __name__ == "__main__":
    project_root = Path(__file__).parent.resolve()

    # 1. Validate the environment. If it's not valid, run the setup.
    if not is_environment_valid(project_root):
        print("--- Environment is invalid or not yet set up. Running installation... ---")
        print("This may take several minutes.")

        setup_script_path = str(project_root / "configuration" / "setup.py")
        run_command([sys.executable, setup_script_path])

        print("\n--- Environment setup complete. ---")
        print("--- Starting the main pipeline... ---")
    else:
        print("--- Environment already set up. Starting main pipeline... ---")

    # 2. Run the main pipeline script.
    main_script_path = str(project_root / "main.py")
    run_command([sys.executable, main_script_path])
