name: ppi-env # This is a default name, the user can override it.
channels:
  # Add the nvidia channel to find the CUDA toolkit.
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # --- Base Environment & Libraries from Conda ---
  - python=3.11
  # Pin CUDA to a version well-supported by both Torch and TF
  - cudatoolkit=12.1
  - cudnn
  - dask
  - tqdm
  - biopython
  - scikit-learn
  - scipy
  - gensim
  - transformers # The HuggingFace library
  - requests
  - pyarrow
  - matplotlib
  - seaborn
  - python-louvain
  - pip